### ISSUE TITLE
Замечания и предложения

### ISSUE THREAD

**Issue by illavaria** [Chembampul/TRITPO2#1]
В пункте 3.1.1.5 указано, что при помещении арендатора в чёрный список, любые его заявки на бронирование у арендодателя, поместившего его в чёрный список, будут блокироваться. Как вариант, можно при помещении арендатора в чёрный список не отображать ему варианты жилья заблокировавшего арендодателя. 
На mockup вкладка «Перечень доступных мест» не совсем рациональное использование пространства: достаточно много пустого пространства с правой стороны.

**Comment by Chembampul** [comment]
Технология, описанная в первом пункте замечаний, уже будет реализована для арендатора в случае, если он поместит арендодателя в чёрный список, поэтому, при желании заказчика, не составит проблем добавить эту технологию и на сторону арендодателя.
Замечания из второго пункта будут учтены при дальнейшей разработке проекта в процессе написания интерфейса.
