### ISSUE TITLE
Замечания и предложения

### ISSUE THREAD

**Issue by NAsQuk** [Chembampul/TRITPO2#2]
Пункт 1.2.3 Необходимо уточнить к какому типу пользователей относится арендатор( зарегистрированный или пользователь без регистрации). 
В пункте 1.3 можно более подробно расписать аналоги и хотя бы одно отличие их от разрабатываемого приложения.
Пункт 2.4 Доступ к сети Интернет есть не только у компьютера и телефона, лучше заменить их на  "устройства с доступом к сети Интернет".

**Comment by Chembampul** [comment]
Недочёты приняты к сведению и исправлены.
